### PR TITLE
Add new blog: Setup of NETCONF client and server

### PR DESCRIPTION
**Pull request by emihas**

### CODE REVIEW

**Comment by troglobit** [comment]
Re: IPv6, maybe add a small note about how to find the IPv6 address of a remote device on a link?  Something small and simple like this:

```sh
ping -6 -L -c1 ff02::1%virbr0 | awk '/64 bytes from/{print $4 $5}' |sed 's/\(.*\):icmp_seq.*/\1/'
```

**Comment by emihas** [comment]
> Re: IPv6, maybe add a small note about how to find the IPv6 address of a remote device on a link? Something small and simple like this:
> 
> ```shell
> ping -6 -L -c1 ff02::1%virbr0 | awk '/64 bytes from/{print $4 $5}' |sed 's/\(.*\):icmp_seq.*/\1/'
> ```

Added this in the last commit.

**Comment by troglobit** [comment]
@jovatn let me know if you need help reviewing.

**Comment by troglobit** [comment]
Awesome work on this, @emihas! :sunglasses::+1:

**Pull request merged**
